FROM node:14

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG DEFAULT_PORT=80

ENV PORT=${DEFAULT_PORT}

EXPOSE ${PORT}

# VOLUME [ "/app/node_modules" ]

CMD [ "npm" , "start" ]

# - docker run -p 3000:8000 --env-file ./.env -d --rm --name feedback-app -v feedback:/app/feedback -v "D:\coding\docker-complete\data-volumes:/app:ro" -v /app/temp -v /app/node_modules feedback-node:ENV
